# Generated by Django 4.0.2 on 2022-02-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='zip',
            field=models.CharField(default='19013', max_length=20),
        ),
    ]
