# Generated by Django 4.0.2 on 2022-02-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_photo_1_alter_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-list_date',)},
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=25),
        ),
    ]
